# Synopsys Design Constraints (SDC) File
# Audio Visualizer Timing Constraints

# ============================================
# Clock Definitions
# ============================================

# Main system clock - 50 MHz
create_clock -name CLOCK_50 -period 20.000 [get_ports CLOCK_50]

# Audio bit clock (BCLK) - External clock from WM8731
# Typical frequency: ~3.072 MHz for 48kHz sample rate
# Period ~325ns, but we'll be lenient as it's asynchronous
create_clock -name AUD_BCLK -period 325.000 [get_ports AUD_BCLK]

# Audio master clock (XCK) - Generated by PLL, 12.288 MHz
create_generated_clock -name AUD_XCK \
    -source [get_pins {pll_inst|pll_audio_inst|altera_pll_i|general[0].gpll~PLL_OUTPUT_COUNTER|divclk}] \
    -divide_by 1 \
    [get_ports AUD_XCK]

# Note: The above PLL path may need adjustment based on actual PLL IP generation
# Alternative simpler constraint if the above path doesn't work:
# create_clock -name AUD_XCK -period 81.380 [get_ports AUD_XCK]

# ============================================
# Clock Groups - Set asynchronous domains
# ============================================

# BCLK is asynchronous to system clock
set_clock_groups -asynchronous \
    -group [get_clocks CLOCK_50] \
    -group [get_clocks AUD_BCLK]

# ============================================
# Input Delays
# ============================================

# Audio data input timing relative to BCLK
# I2S data is valid for setup before and hold after BCLK edge
set_input_delay -clock AUD_BCLK -max 10.000 [get_ports AUD_ADCDAT]
set_input_delay -clock AUD_BCLK -min 5.000 [get_ports AUD_ADCDAT]

set_input_delay -clock AUD_BCLK -max 10.000 [get_ports AUD_ADCLRCK]
set_input_delay -clock AUD_BCLK -min 5.000 [get_ports AUD_ADCLRCK]

# Push button inputs (KEY) - no critical timing
set_input_delay -clock CLOCK_50 -max 5.000 [get_ports KEY[*]]
set_input_delay -clock CLOCK_50 -min 0.000 [get_ports KEY[*]]

# Switch inputs - no critical timing
set_input_delay -clock CLOCK_50 -max 5.000 [get_ports SW[*]]
set_input_delay -clock CLOCK_50 -min 0.000 [get_ports SW[*]]

# ============================================
# Output Delays
# ============================================

# LED outputs - no critical timing requirement
set_output_delay -clock CLOCK_50 -max 5.000 [get_ports LEDR[*]]
set_output_delay -clock CLOCK_50 -min 0.000 [get_ports LEDR[*]]

# I2C outputs - controlled by internal state machine
set_output_delay -clock CLOCK_50 -max 10.000 [get_ports FPGA_I2C_SCLK]
set_output_delay -clock CLOCK_50 -min 0.000 [get_ports FPGA_I2C_SCLK]

set_output_delay -clock CLOCK_50 -max 10.000 [get_ports FPGA_I2C_SDAT]
set_output_delay -clock CLOCK_50 -min 0.000 [get_ports FPGA_I2C_SDAT]

# Audio DAC outputs (unused but constrained)
set_output_delay -clock CLOCK_50 -max 10.000 [get_ports AUD_DACDAT]
set_output_delay -clock CLOCK_50 -min 0.000 [get_ports AUD_DACDAT]

set_output_delay -clock CLOCK_50 -max 10.000 [get_ports AUD_DACLRCK]
set_output_delay -clock CLOCK_50 -min 0.000 [get_ports AUD_DACLRCK]

# ============================================
# False Paths
# ============================================

# Reset signal is asynchronous
set_false_path -from [get_ports KEY[0]] -to [all_registers]

# I2C configuration is not timing-critical
set_false_path -to [get_ports FPGA_I2C_SCLK]
set_false_path -to [get_ports FPGA_I2C_SDAT]
set_false_path -from [get_ports FPGA_I2C_SDAT]

# ============================================
# Multicycle Paths
# ============================================

# Allow more time for LED updates (not timing critical)
set_multicycle_path -to [get_ports LEDR[*]] -setup 2
set_multicycle_path -to [get_ports LEDR[*]] -hold 1

# ============================================
# Maximum Delay Constraints
# ============================================

# Ensure synchronizer chains complete within one clock period
set_max_delay -from [get_ports AUD_BCLK] -to [all_registers] 20.000
set_max_delay -from [get_ports AUD_ADCLRCK] -to [all_registers] 20.000
set_max_delay -from [get_ports AUD_ADCDAT] -to [all_registers] 20.000
